<template>
    <div class="content">
        <h1>
            Error responses from the cdnjs API
        </h1>
        <p>
            All errors generated by using the cdnjs API will return with a unified structure for easy detection
            &amp; processing. They will return a JSON object containing the error status code as well as a message
            explaining the error. The HTTP response code will also reflect the error.
        </p>
        <p>
            404 error responses will have a 1 hour cache lifetime, all other errors (5xx etc.) have no cache
            lifetime set.
        </p>
    </div>
</template>

<script>
    export default {
        name: 'APIErrorsHeader',
    };
</script>
