<template>
    <div>
        <h2 id="errors">
            Error responses from the cdnjs API
        </h2>
        <div class="doc">
            <p>
                All errors generated by using the cdnjs API will return with a unified structure for easy detection
                &amp; processing. They will return a JSON object containing the error status code as well as a message
                explaining the error. The HTTP response code will also reflect the error.
            </p>
            <p>
                404 error responses will have a 1 hour cache lifetime, all other errors (5xx etc.) have no cache
                lifetime set.
            </p>

            <h3>JSON Response</h3>
            <table>
                <thead>
                    <tr>
                        <th>Property</th>
                        <th>Type</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="field in response">
                        <td><code class="key">{{ field.prop }}</code></td>
                        <td>
                            <template v-for="type in field.type">
                                <code class="key">{{ type }}</code>&nbsp;
                            </template>
                        </td>
                        <td>
                            <p v-for="desc in field.desc" v-html="desc"></p>
                        </td>
                    </tr>
                </tbody>
            </table>

            <h3>Example Requests</h3>

            <h4>
                <a href="https://api.cdnjs.com/libraries/this-library-doesnt-exist">
                    <code class="key">https://api.cdnjs.com/libraries/this-library-doesnt-exist</code>
                </a>
            </h4>
            <JSONExample>{"error":true,"status":404,"message":"Library not found"}</JSONExample>

            <h4>
                <a href="https://api.cdnjs.com/this-route-doesnt-exist">
                    <code class="key">https://api.cdnjs.com/this-route-doesnt-exist</code>
                </a>
            </h4>
            <JSONExample>{"error":true,"status":404,"message":"Endpoint not found"}</JSONExample>
        </div>
    </div>
</template>

<script>
    import JSONExample from '../json_example';

    export default {
        name: 'APIErrors',
        components: {
            JSONExample,
        },
        data () {
            return {
                response: [
                    {
                        prop: 'error',
                        type: [
                            'boolean',
                        ],
                        desc: [
                            'This will always be set to <code>true</code> to indicate that an error has occurred.',
                        ],
                    },
                    {
                        prop: 'status',
                        type: [
                            'integer',
                        ],
                        desc: [
                            'The status code for the error, which should be identical to the HTTP response status code.',
                        ],
                    },
                    {
                        prop: 'message',
                        type: [
                            'string',
                        ],
                        desc: [
                            'A message explaining what error has occurred.',
                        ],
                    },
                ],
            };
        },
    };
</script>
