name: Test Latest Commit

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Build Site
      run: SITE_HOST=http://localhost:3000/ npm run build

    - name: Check Site
      run: |
        trap 'kill $(jobs -p)' EXIT
        SITE_HOST=http://localhost:3000/ npm run start &
        sleep 5
        curl -fsSI http://localhost:3000/
